      - name: Build
        run: gradle setupCIWorkspace build --no-daemon

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: VapeVlite
          path: build/libs/*.jar
